@startuml

left to right direction

actor Player
actor Administrator
package "Card System" {
  usecase "Draw Card"
  usecase "Play Card"
  usecase "See Card"
  usecase "Hold Card"
  usecase "Show Building costs Card"
  usecase "Shuffle Cards"
  usecase "Add to Deck"
  usecase "Get Building Card"
  usecase "Remove Card"
}

Player -- "Draw Card"
Player -l- "Show Building costs Card"
Player -- "Play Card"
Player -- "Hold Card"
Player -- "Get Building Card"
Administrator -- "Shuffle Cards"
Administrator -- "Add to Deck"
Administrator -- "Remove Card"
Administrator --|> Player

"Play Card" ..> "Draw Card" : <<extend>>
"Get Building Card" ..> "Play Card" : <<extend>>
"Draw Card" ..> "See Card" : <<include>>
"Hold Card" ..> "See Card" : <<extend>>
"Show Building costs Card" ..> "See Card" : <<extend>>
"Shuffle Cards" ..> "Add to Deck" : <<include>>
"Remove Card" ..> "Draw Card" : <<extend>>
note top of "Draw Card" : F5.3 \nDeck::drawCard()
note bottom of "Play Card" : F5.6 \nCard::playCard()
note right of "See Card" : F5.5 \nCard::seeCard()
note top of "Hold Card" : F5.4 \nCard::holdCard()
note top of "Show Building costs Card" : F5.7.3 \nBuildingCostsCard::showBuildingCostsCard()
note left of "Shuffle Cards" : F5.1 \nDeck::shuffleCards()
note bottom of "Add to Deck" : F5.2 \nDeck::addToDeck()
note left of "Get Building Card" : F5.7.1 \nBuildingCard::getBuildingCard()
note top of "Remove Card" : F5.7.2 \nDeck::removeCard()
@enduml
